#!/usr/bin/env bash
# scripts/setup.sh
# Run from the repo root: bash scripts/setup.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# ── Directories ───────────────────────────────────────────────
echo "📁  Creating directories..."
mkdir -p "$REPO_ROOT/data/enterprise"
mkdir -p "$REPO_ROOT/data/plugins"
mkdir -p "$REPO_ROOT/data/explorer"
mkdir -p "$REPO_ROOT/config"
echo "✅  Directories created."
echo ""

# ── .env ──────────────────────────────────────────────────────
if [ -f "$REPO_ROOT/.env" ]; then
  echo "ℹ️   .env already exists — skipping."
else
  cp "$REPO_ROOT/.env.example" "$REPO_ROOT/.env"

  # Generate Explorer session secret
  SESSION_SECRET=$(openssl rand -hex 32)
  sed -i.bak "s|EXPLORER_SESSION_SECRET_KEY=.*|EXPLORER_SESSION_SECRET_KEY=$SESSION_SECRET|" "$REPO_ROOT/.env"
  rm -f "$REPO_ROOT/.env.bak"
  echo "📋  .env created from .env.example"
  echo "✅  EXPLORER_SESSION_SECRET_KEY auto-generated"
fi
echo ""

# ── Admin token ───────────────────────────────────────────────
TOKEN_FILE="$REPO_ROOT/config/admin-token.json"

if [ -f "$TOKEN_FILE" ]; then
  echo "ℹ️   config/admin-token.json already exists — skipping token generation."
  # Read existing token back to update .env and config.json below
  TOKEN=$(python3 -c "import json; print(json.load(open('$TOKEN_FILE'))['token'])" 2>/dev/null \
    || grep -o '"apiv3_[^"]*"' "$TOKEN_FILE" | tr -d '"')
else
  # Generate a cryptographically secure token: apiv3_ + 32 random bytes base64-encoded
  TOKEN="apiv3_$(openssl rand -base64 32 | tr -d '=+/' | cut -c1-43)"

  cat > "$TOKEN_FILE" << JSONEOF
{
  "token": "$TOKEN",
  "name": "admin",
  "description": "Admin token pre-generated by setup.sh"
}
JSONEOF
  chmod 600 "$TOKEN_FILE"
  echo "🔑  Admin token generated → config/admin-token.json"
fi
echo ""

# ── Write token into .env ──────────────────────────────────────
sed -i.bak "s|INFLUXDB3_AUTH_TOKEN=.*|INFLUXDB3_AUTH_TOKEN=$TOKEN|" "$REPO_ROOT/.env"
rm -f "$REPO_ROOT/.env.bak"
echo "✅  INFLUXDB3_AUTH_TOKEN written to .env"

# ── Write config/config.json for Explorer ─────────────────────
cat > "$REPO_ROOT/config/config.json" << JSONEOF
{
  "DEFAULT_INFLUX_SERVER": "http://demo-influxdb3-enterprise:8181",
  "DEFAULT_SERVER_NAME": "InfluxDB 3 Enterprise (local)",
  "DEFAULT_API_TOKEN": "$TOKEN"
}
JSONEOF
echo "✅  config/config.json written with admin token"
echo ""

# ── Done ──────────────────────────────────────────────────────
echo "────────────────────────────────────────────────"
echo "  One thing left: open .env and set your email"
echo ""
echo "  INFLUXDB3_ENTERPRISE_LICENSE_EMAIL=you@example.com"
echo ""
echo "  Then start the stack:"
echo "  docker compose up -d"
echo "────────────────────────────────────────────────"
